//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhilipDaubmeier.DigitalstromClient.Locale {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scene {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scene() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhilipDaubmeier.DigitalstromClient.Locale.Scene", typeof(Scene).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original translations extracted from translation files of the digitalSTROM server installer ui:
        ///https://git.digitalstrom.org/dss-websrc/dss-websrc-mainline/blob/master/webroot/locale/
        ///Copyright (c) 2020 digitalSTROM.org, Zurich, Switzerland ähnelt.
        /// </summary>
        internal static string _Authors {
            get {
                return ResourceManager.GetString("_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm 1 ähnelt.
        /// </summary>
        internal static string Alarm1 {
            get {
                return ResourceManager.GetString("Alarm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm 2 ähnelt.
        /// </summary>
        internal static string Alarm2 {
            get {
                return ResourceManager.GetString("Alarm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm 3 ähnelt.
        /// </summary>
        internal static string Alarm3 {
            get {
                return ResourceManager.GetString("Alarm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alarm 4 ähnelt.
        /// </summary>
        internal static string Alarm4 {
            get {
                return ResourceManager.GetString("Alarm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area 1 off ähnelt.
        /// </summary>
        internal static string Area1Off {
            get {
                return ResourceManager.GetString("Area1Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area 1 on ähnelt.
        /// </summary>
        internal static string Area1On {
            get {
                return ResourceManager.GetString("Area1On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area 2 off ähnelt.
        /// </summary>
        internal static string Area2Off {
            get {
                return ResourceManager.GetString("Area2Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area 2 on ähnelt.
        /// </summary>
        internal static string Area2On {
            get {
                return ResourceManager.GetString("Area2On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area 3 off ähnelt.
        /// </summary>
        internal static string Area3Off {
            get {
                return ResourceManager.GetString("Area3Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area 3 on ähnelt.
        /// </summary>
        internal static string Area3On {
            get {
                return ResourceManager.GetString("Area3On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area 4 off ähnelt.
        /// </summary>
        internal static string Area4Off {
            get {
                return ResourceManager.GetString("Area4Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Area 4 on ähnelt.
        /// </summary>
        internal static string Area4On {
            get {
                return ResourceManager.GetString("Area4On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fade off ähnelt.
        /// </summary>
        internal static string AutoOff {
            get {
                return ResourceManager.GetString("AutoOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto Standby ähnelt.
        /// </summary>
        internal static string AutoStandby {
            get {
                return ResourceManager.GetString("AutoStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coming Home ähnelt.
        /// </summary>
        internal static string ComingHome {
            get {
                return ResourceManager.GetString("ComingHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dim Down ähnelt.
        /// </summary>
        internal static string DimDown {
            get {
                return ResourceManager.GetString("DimDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dim Up ähnelt.
        /// </summary>
        internal static string DimUp {
            get {
                return ResourceManager.GetString("DimUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Door Bell ähnelt.
        /// </summary>
        internal static string Doorbell {
            get {
                return ResourceManager.GetString("Doorbell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fire ähnelt.
        /// </summary>
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gas ähnelt.
        /// </summary>
        internal static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hail ähnelt.
        /// </summary>
        internal static string Hail {
            get {
                return ResourceManager.GetString("Hail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impulse ähnelt.
        /// </summary>
        internal static string Impulse {
            get {
                return ResourceManager.GetString("Impulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leaving Home ähnelt.
        /// </summary>
        internal static string LeaveHome {
            get {
                return ResourceManager.GetString("LeaveHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max ähnelt.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min ähnelt.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No hail ähnelt.
        /// </summary>
        internal static string Nohail {
            get {
                return ResourceManager.GetString("Nohail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No rain ähnelt.
        /// </summary>
        internal static string NoRain {
            get {
                return ResourceManager.GetString("NoRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No wind ähnelt.
        /// </summary>
        internal static string Nowind {
            get {
                return ResourceManager.GetString("Nowind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Panic ähnelt.
        /// </summary>
        internal static string Panic {
            get {
                return ResourceManager.GetString("Panic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rain ähnelt.
        /// </summary>
        internal static string Rain {
            get {
                return ResourceManager.GetString("Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room off ähnelt.
        /// </summary>
        internal static string RoomOff {
            get {
                return ResourceManager.GetString("RoomOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 1 ähnelt.
        /// </summary>
        internal static string Scene1 {
            get {
                return ResourceManager.GetString("Scene1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 10 ähnelt.
        /// </summary>
        internal static string Scene10 {
            get {
                return ResourceManager.GetString("Scene10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 11 ähnelt.
        /// </summary>
        internal static string Scene11 {
            get {
                return ResourceManager.GetString("Scene11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 12 ähnelt.
        /// </summary>
        internal static string Scene12 {
            get {
                return ResourceManager.GetString("Scene12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 13 ähnelt.
        /// </summary>
        internal static string Scene13 {
            get {
                return ResourceManager.GetString("Scene13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 14 ähnelt.
        /// </summary>
        internal static string Scene14 {
            get {
                return ResourceManager.GetString("Scene14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 2 ähnelt.
        /// </summary>
        internal static string Scene2 {
            get {
                return ResourceManager.GetString("Scene2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 20 ähnelt.
        /// </summary>
        internal static string Scene20 {
            get {
                return ResourceManager.GetString("Scene20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 21 ähnelt.
        /// </summary>
        internal static string Scene21 {
            get {
                return ResourceManager.GetString("Scene21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 22 ähnelt.
        /// </summary>
        internal static string Scene22 {
            get {
                return ResourceManager.GetString("Scene22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 23 ähnelt.
        /// </summary>
        internal static string Scene23 {
            get {
                return ResourceManager.GetString("Scene23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 24 ähnelt.
        /// </summary>
        internal static string Scene24 {
            get {
                return ResourceManager.GetString("Scene24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 3 ähnelt.
        /// </summary>
        internal static string Scene3 {
            get {
                return ResourceManager.GetString("Scene3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 30 ähnelt.
        /// </summary>
        internal static string Scene30 {
            get {
                return ResourceManager.GetString("Scene30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 31 ähnelt.
        /// </summary>
        internal static string Scene31 {
            get {
                return ResourceManager.GetString("Scene31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 32 ähnelt.
        /// </summary>
        internal static string Scene32 {
            get {
                return ResourceManager.GetString("Scene32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 33 ähnelt.
        /// </summary>
        internal static string Scene33 {
            get {
                return ResourceManager.GetString("Scene33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 34 ähnelt.
        /// </summary>
        internal static string Scene34 {
            get {
                return ResourceManager.GetString("Scene34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 4 ähnelt.
        /// </summary>
        internal static string Scene4 {
            get {
                return ResourceManager.GetString("Scene4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 40 ähnelt.
        /// </summary>
        internal static string Scene40 {
            get {
                return ResourceManager.GetString("Scene40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 41 ähnelt.
        /// </summary>
        internal static string Scene41 {
            get {
                return ResourceManager.GetString("Scene41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 42 ähnelt.
        /// </summary>
        internal static string Scene42 {
            get {
                return ResourceManager.GetString("Scene42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 43 ähnelt.
        /// </summary>
        internal static string Scene43 {
            get {
                return ResourceManager.GetString("Scene43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset 44 ähnelt.
        /// </summary>
        internal static string Scene44 {
            get {
                return ResourceManager.GetString("Scene44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sleeping ähnelt.
        /// </summary>
        internal static string Sleeping {
            get {
                return ResourceManager.GetString("Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smoke ähnelt.
        /// </summary>
        internal static string Smoke {
            get {
                return ResourceManager.GetString("Smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standby ähnelt.
        /// </summary>
        internal static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wake Up ähnelt.
        /// </summary>
        internal static string Wakeup {
            get {
                return ResourceManager.GetString("Wakeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Water ähnelt.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wind ähnelt.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
    }
}
