//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhilipDaubmeier.DigitalstromClient.Locale {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sensor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sensor() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhilipDaubmeier.DigitalstromClient.Locale.Sensor", typeof(Sensor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original translations extracted from translation files of the digitalSTROM server installer ui:
        ///https://git.digitalstrom.org/dss-websrc/dss-websrc-mainline/blob/master/webroot/locale/
        ///Copyright (c) 2020 digitalSTROM.org, Zurich, Switzerland ähnelt.
        /// </summary>
        internal static string _Authors {
            get {
                return ResourceManager.GetString("_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active power [W] ähnelt.
        /// </summary>
        internal static string ActivePower {
            get {
                return ResourceManager.GetString("ActivePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Air pressure [hPa] ähnelt.
        /// </summary>
        internal static string AirPressure {
            get {
                return ResourceManager.GetString("AirPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness ähnelt.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness indoors [lux] ähnelt.
        /// </summary>
        internal static string BrightnessIndoors {
            get {
                return ResourceManager.GetString("BrightnessIndoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness outdoors [lux] ähnelt.
        /// </summary>
        internal static string BrightnessOutdoors {
            get {
                return ResourceManager.GetString("BrightnessOutdoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carbon dioxide concentration [ppm] ähnelt.
        /// </summary>
        internal static string CarbonDioxideConcentration {
            get {
                return ResourceManager.GetString("CarbonDioxideConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carbon monoxide concentration [ppm] ähnelt.
        /// </summary>
        internal static string CarbonMonoxideConcentration {
            get {
                return ResourceManager.GetString("CarbonMonoxideConcentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Electric meter [kWh] ähnelt.
        /// </summary>
        internal static string ElectricMeter {
            get {
                return ResourceManager.GetString("ElectricMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cool ähnelt.
        /// </summary>
        internal static string NotUsed {
            get {
                return ResourceManager.GetString("NotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output current [mA] ähnelt.
        /// </summary>
        internal static string OutputCurrent {
            get {
                return ResourceManager.GetString("OutputCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output current (H) [mA] ähnelt.
        /// </summary>
        internal static string OutputCurrentH {
            get {
                return ResourceManager.GetString("OutputCurrentH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Power consumption [VA] ähnelt.
        /// </summary>
        internal static string PowerConsumption {
            get {
                return ResourceManager.GetString("PowerConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Precipitation [mm/m2] ähnelt.
        /// </summary>
        internal static string Precipitation {
            get {
                return ResourceManager.GetString("Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relative humidity ähnelt.
        /// </summary>
        internal static string RelativeHumidity {
            get {
                return ResourceManager.GetString("RelativeHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relative humidity indoors [%] ähnelt.
        /// </summary>
        internal static string RelativeHumidityIndoors {
            get {
                return ResourceManager.GetString("RelativeHumidityIndoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relative humidity outdoors [%] ähnelt.
        /// </summary>
        internal static string RelativeHumidityOutdoors {
            get {
                return ResourceManager.GetString("RelativeHumidityOutdoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reserved ähnelt.
        /// </summary>
        internal static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room temperature control [%] ähnelt.
        /// </summary>
        internal static string RoomTemperatureControl {
            get {
                return ResourceManager.GetString("RoomTemperatureControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Room temperature setpoint [°C] ähnelt.
        /// </summary>
        internal static string RoomTemperatureSetpoint {
            get {
                return ResourceManager.GetString("RoomTemperatureSetpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound Pressure Level ähnelt.
        /// </summary>
        internal static string SoundPressureLevel {
            get {
                return ResourceManager.GetString("SoundPressureLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sun azimuth [° degrees] ähnelt.
        /// </summary>
        internal static string SunAzimuth {
            get {
                return ResourceManager.GetString("SunAzimuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sun elevation [° degrees] ähnelt.
        /// </summary>
        internal static string SunElevation {
            get {
                return ResourceManager.GetString("SunElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature ähnelt.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature indoors [°C] ähnelt.
        /// </summary>
        internal static string TemperatureIndoors {
            get {
                return ResourceManager.GetString("TemperatureIndoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperature outdoors [°C] ähnelt.
        /// </summary>
        internal static string TemperatureOutdoors {
            get {
                return ResourceManager.GetString("TemperatureOutdoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wind direction [° degrees] ähnelt.
        /// </summary>
        internal static string WindDirection {
            get {
                return ResourceManager.GetString("WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wind gust direction [° degrees] ähnelt.
        /// </summary>
        internal static string WindGustdirection {
            get {
                return ResourceManager.GetString("WindGustdirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wind gust speed [m/s] ähnelt.
        /// </summary>
        internal static string WindGustspeed {
            get {
                return ResourceManager.GetString("WindGustspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wind speed [m/s] ähnelt.
        /// </summary>
        internal static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
    }
}
